// utils/gallerySlides.ts
export const slides = [
  {
    id: 1,
    src: "/gallery/1.jpeg",
    alt: "Gallery image 1",
    title: "Gallery Image 1",
  },
  {
    id: 2,
    src: "/gallery/2.jpeg",
    alt: "Gallery image 2",
    title: "Gallery Image 2",
  },
  {
    id: 3,
    src: "/gallery/3.jpeg",
    alt: "Gallery image 3",
    title: "Gallery Image 3",
  },
  {
    id: 4,
    src: "/gallery/4.jpeg",
    alt: "Gallery image 4",
    title: "Gallery Image 4",
  },
  {
    id: 5,
    src: "/gallery/5.jpeg",
    alt: "Gallery image 5",
    title: "Gallery Image 5",
  },
  {
    id: 6,
    src: "/gallery/6.jpeg",
    alt: "Gallery image 6",
    title: "Gallery Image 6",
  },
  {
    id: 7,
    src: "/gallery/7.jpeg",
    alt: "Gallery image 7",
    title: "Gallery Image 7",
  },
  {
    id: 8,
    src: "/gallery/8.jpeg",
    alt: "Gallery image 8",
    title: "Gallery Image 8",
  },
  {
    id: 9,
    src: "/gallery/9.jpeg",
    alt: "Gallery image 9",
    title: "Gallery Image 9",
  },
  {
    id: 10,
    src: "/gallery/10.jpeg",
    alt: "Gallery image 10",
    title: "Gallery Image 10",
  },
  {
    id: 11,
    src: "/gallery/11.jpeg",
    alt: "Gallery image 11",
    title: "Gallery Image 11",
  },
  {
    id: 12,
    src: "/gallery/12.jpeg",
    alt: "Gallery image 12",
    title: "Gallery Image 12",
  },
  {
    id: 13,
    src: "/gallery/13.jpeg",
    alt: "Gallery image 13",
    title: "Gallery Image 13",
  },
  {
    id: 14,
    src: "/gallery/14.jpeg",
    alt: "Gallery image 14",
    title: "Gallery Image 14",
  },
  {
    id: 15,
    src: "/gallery/15.jpeg",
    alt: "Gallery image 15",
    title: "Gallery Image 15",
  },
  {
    id: 16,
    src: "/gallery/16.jpeg",
    alt: "Gallery image 16",
    title: "Gallery Image 16",
  },
  {
    id: 17,
    src: "/gallery/17.jpeg",
    alt: "Gallery image 17",
    title: "Gallery Image 17",
  },
  {
    id: 18,
    src: "/gallery/18.jpeg",
    alt: "Gallery image 18",
    title: "Gallery Image 18",
  },
  {
    id: 19,
    src: "/gallery/19.jpeg",
    alt: "Gallery image 19",
    title: "Gallery Image 19",
  },
  {
    id: 20,
    src: "/gallery/20.jpeg",
    alt: "Gallery image 20",
    title: "Gallery Image 20",
  },
  {
    id: 21,
    src: "/gallery/21.jpeg",
    alt: "Gallery image 21",
    title: "Gallery Image 21",
  },
  {
    id: 22,
    src: "/gallery/22.jpeg",
    alt: "Gallery image 22",
    title: "Gallery Image 22",
  },
  {
    id: 23,
    src: "/gallery/23.jpeg",
    alt: "Gallery image 23",
    title: "Gallery Image 23",
  },
  {
    id: 24,
    src: "/gallery/24.jpeg",
    alt: "Gallery image 24",
    title: "Gallery Image 24",
  },
];
